export const STRINGCONSTANT = {
  APP: {
    LETS: "Let's",
    START: 'Get Started',
    HANDLE: 'handled',
    HEY: 'Hey,',
    WELCOME: 'Welcome Back',
    RULES: 'Rules & Description',
    LINES4: 4,
    LINES1: 1,
    NA : 'N/A',
    RESET_PASSWORD : 'Reset Your Password'
  },
  LABELS: {
    EMAIL: 'Email',
    NAME: 'Name',
    NEW_PASSWORD: 'New Password',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    FORGOT_PASSWORD: 'Forgot Password?',
    SLOT_REMAIN: 'Slots Remaining:',
    FORMAT: 'Format:',
    EVENT_TITLE: 'Event Title *',
    EVENT_DATE: 'Date *',
    EVENT_TIME: 'Time *',
    EVENT_IMAGE: 'Select Image *',
    DESCRIPTION: 'Description',
    SLOT: 'Slot',
    PLAYER_DETAILS : 'Player Details',
    GENDER : 'Gender',
    ROUND : 'Round',
    SLOT1 : 'Slot 2 vs 2:',
    SLOT2 : 'Slot 1 vs 1:',
    MATCH_TYPE : 'Match Type',
    NOT_FOUND : 'No events found',
    MALE_PLAYER : 'Male Players',
    FEMALE_PLAYER : 'Female Players',
    NO_PLAYER : 'No Player found',
    ZERO : 0,
    KNOCKOUT : 'knockout',
    ROUNDROBIN : 'roundrobin',
    SELECT_SLOT : 'Select Slot',
    MY_EVENT : 'My Events',
    TOTAL_EVENT : 'Total Events',
    USERS : 'Users'

  },
  PLACEHOLDERS: {
    EMAIL: 'Enter your email',
    PASSWORD: 'Enter your password',
    NAME: 'Enter your name',
    CREATE_PASSWORD: 'Create a password',
    NEW_PASSWORD: 'Enter new password',
    CONFIRM_PASSWORD: 'Enter Confirm Password',
    SEARCH_EVENT: 'Search Events',
    EVENT_TITLE: 'Enter event title',
    EVENT_DATE: '2026-12-04',
    EVENT_TIME: '10:00 AM',
    FORMAT: '1 vs 1 or 2 vs 2',
    SLOT: '10',
    DESCRIPTION: 'Enter event description',
    PHONE_NUMBER : 'Phone Number',
  },
  ACCOUNT: {
    ALREADY_ACOOUNT: 'Already have an account? ',
    NO_ACCOUNT: "Dont't have an account? ",
  },
  BUTTONS: {
    CREATE: 'Create Account',
    LOGIN: 'Login',
    UPDATE: 'Update Password',
    SUBMIT: 'Submit',
    SIGNUP: 'Sign Up',
    REGISTER: 'Register',
    NEXT: 'Next',
    JOIN_EVENT: 'Join Event',
    EDIT_EVENT: 'Edit Event',
    CREATE_EVENT: 'Create Event',
    LOGOUT: 'Logout',
    DELETE : 'Delete',
    EDIT : 'Edit',
    CREATE_BUTTON : 'create',
    UPCOMING : 'upcoming',
    COMPLETED : 'completed',
    TODAY : 'today',
    JOIN : 'Join',
    FIXTURES : 'Fixtures',
    TEAM_LISTING : "Team Listing",
    DONE : 'Done',
  },
  USER_INFO: {
    TITLE_ADMIN: 'Admin',
    ICON_ADMIN: 'admin-panel-settings',
    DESCRIPTION_ADMIN:
      'Admins have full access to the system. They can manage users monitor activities',
    TITLE_ORGANISER: 'Organizer',
    ICON_ORGANISER: 'event',
    DESCRIPTION_ORGANISER:
      'Organizers can create, update, and manage events. They handle registrations, schedule of event',
    TITLE_PARTICIPANTS: 'Participant',
    ICON_PARTICIPANTS: 'person',
    DESCRIPTION_PARTICIPANTS:
      'Participants can browse events, register, receive notifications, and actively take part in activities.',
  },
  USER_ROLE: {
    SELECT_ROLE: 'Select Your Role',
    CHOOSE_ROLE: 'Choose how you’ll use the app',
    ICON_SIZE: 28,
  },
  KEYBOARD_TYPE : {
    PHONE_PAD : 'phone-pad',
  } as const,
  ICON: {
    ADD: 'add',
    SEARCH: 'search',
    LOGIN: 'login',
    DELETE: 'delete',
    EDIT: 'edit',
    TENNIS: 'sports-tennis',
    GROUP: 'group',
    CALENDER: 'calendar-today',
    ACCESS_TIME: 'access-time',
    PERSON: 'person',
    VISIBILITY : 'visibility',
    VISIBILITY_OFF : 'visibility-off',
    DESCRIPTION : "description",
    LOOKS1 : "looks-two",
    LOOKS2 : "looks-one",
    ARROW_DOWN : "arrow-drop-down",
  },
  ROLE: {
    ADMIN: 'admin',
    ORGANISER: 'organiser',
    PARTICIPANT : 'participant',
    USER : 'User',
  },
  TYPES : {
    STRING : 'string'
  },
  HEADER: {
    EVENT: 'Events',
    EVENT_DETAIL: 'Event Details',
    EDIT_EVENT: 'Edit Event',
    CREATE_EVENT: 'Create Event',
    USER_MANAGEMENT : "User Management",
    TEAM_REGISTRATION : "Team Registration",
    TEAM_LISTING : 'Teams Listing',
    I_V_I : '1 vs 1 Match',
    II_V_II : '2 vs 2 Match',
    DASHBOARD : 'Dashboard',

  },
  TAB : {
    TODAY : 'today',
    UPCOMING : 'upcoming',
    COMPLETED : 'completed',
    ivi : '1v1',
    iivii : '2v2',
    IvsI : '1 vs 1',
    IIvsII : '2 vs 2',

  },
  TOAST : {
    INFO :'info',
    SUCCESS : 'success',
    ERROR : 'error'
  },
  ARRAY : {
    GENDER :['male', 'female', 'other'] as const,
    FORMAT : ['1v1', '2v2'],
    TABS : ['1v1', '2v2'] as const,
    SLOTOPTIONS : [1, 2, 4, 8, 16, 32, 64],
    DAY : ['today', 'upcoming', 'completed']
  },
  GENDER : {
    MALE : 'Male',
    FEMALE : 'Female'
  }
};
