export const STRING = {
  APP: {
    LETS: "Let's",
    START: 'Get Started',
    HANDLE: 'handled',
    HEY: 'Hey,',
    WELCOME: 'Welcome Back',
    RULES: 'Rules & Description',
    LINES: 4,
    NA : 'N/A'
  },
  LABELS: {
    EMAIL: 'Email',
    NAME: 'Name',
    NEW_PASSWORD: 'New Password',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    FORGOT_PASSWORD: 'Forgot Password?',
    SLOT_REMAIN: 'Slots Remaining:',
    FORMAT: 'Format:',
    EVENT_TITLE: 'Event Title *',
    EVENT_DATE: 'Date *',
    EVENT_TIME: 'Time *',
    EVENT_IMAGE: 'Select Image *',
    DESCRIPTION: 'Description',
    SLOT: 'Slot',
  },
  PLACEHOLDERS: {
    EMAIL: 'Enter your email',
    PASSWORD: 'Enter your password',
    NAME: 'Enter your full name',
    CREATE_PASSWORD: 'Create a password',
    NEW_PASSWORD: 'Enter new password',
    CONFIRM_PASSWORD: 'Enter Confirm Password',
    SEARCH_EVENT: 'Search Events',
    EVENT_TITLE: 'Enter event title',
    EVENT_DATE: '2026-12-04',
    EVENT_TIME: '10:00 AM',
    FORMAT: '1 vs 1 or 2 vs 2',
    SLOT: '10',
    DESCRIPTION: 'Enter event description',
  },
  ACCOUNT: {
    ALREADY_ACOOUNT: 'Already have an account?',
    NO_ACCOUNT: "Dont't have an account",
  },
  BUTTONS: {
    CREATE: 'Create Account',
    LOGIN: 'Login',
    UPDATE: 'Update Password',
    SUBMIT: 'Submit',
    SIGNUP: 'Sign Up',
    REGISTER: 'Register',
    NEXT: 'Next',
    JOIN_EVENT: 'Join Event',
    EDIT_EVENT: 'Edit Event',
    CREATE_EVENT: 'Create Event',
    LOGOUT: 'Logout',
    DELETE : 'Delete',
    EDIT : 'Edit',
    CREATE_BUTTON : 'create',
    UPCOMING : 'upcoming',
    TODAY : 'today',
    JOIN : 'Join'
  },
  USER_INFO: {
    TITLE_ADMIN: 'Admin',
    ICON_ADMIN: 'admin-panel-settings',
    DESCRIPTION_ADMIN:
      'Admins have full access to the system. They can manage users monitor activities',
    TITLE_ORGANISER: 'Organizer',
    ICON_ORGANISER: 'event',
    DESCRIPTION_ORGANISER:
      'Organizers can create, update, and manage events. They handle registrations, schedule of event',
    TITLE_PARTICIPANTS: 'Participant',
    ICON_PARTICIPANTS: 'person',
    DESCRIPTION_PARTICIPANTS:
      'Participants can browse events, register, receive notifications, and actively take part in activities.',
  },
  USER_ROLE: {
    SELECT_ROLE: 'Select Your Role',
    CHOOSE_ROLE: 'Choose how you’ll use the app',
    ICON_SIZE: 28,
  },
  ICON: {
    ADD: 'add',
    SEARCH: 'search',
    LOGIN: 'login',
    DELETE: 'delete',
    EDIT: 'edit',
    TENNIS: 'sports-tennis',
    GROUP: 'group',
    CALENDER: 'calendar-today',
    ACCESS_TIME: 'access-time',
    PERSON: 'person',
  },
  ROLE: {
    ADMIN: 'admin',
    ORGANISER: 'organiser',
  },
  HEADER: {
    EVENT: 'Events',
    EVENT_DETAIL: 'Event Details',
    EDIT_EVENT: 'Edit Event',
    CREATE_EVENT: 'Create Event',
  },
};
