export const VALIDATE_MESSAGES = {
  INVALID_EMAIL: 'Enter a valid email',
  REQUIRED_EMAIL: 'Email is required',
  NAME_ALPHA_ONLY: 'Name should contain only alphabets',
  NAME_REQUIRED: 'Name is required',
  PASSWORD_REQUIRED: 'Password is required',
  CONFIRM_PASSWORD: 'Confirm password required',
  PASSWORD_MISMATCH: 'Passwords do not match',
  LOGIN_FAILED: 'Login failed',
  LOGIN_SUCCESS: 'Login Successfully',
  REGISTRATION_FAILED: 'Registration Failed',
  REGISTRATION_SUCCESS: 'Register Successfully',
  PASSWORD_UPDATED: 'Password updated',
  PASSWORD_UPDATED_DESCRIPTION: 'Your password has been successfully updated',
  INVALID_PASSWORD:
    'Password must be at least 8 characters long and include uppercase, lowercase, number, and special character.',
  USER_NOT_EXIST: "User doesn't exist",
  USER_ALREADY_EXIST: 'User already exist',
  LOGOUT_FAILED: 'Logout failed',
  DELETED: 'Event Deleted',
  FIELD_REQUIRED: 'All fields are required',
  EVENT_CREATED: 'Event created successfully',
  EVENT_EDITED: 'Event edit successfully',
  DELETE: 'Delete Event',
  CONFIRM_DELETE: 'Are you sure you want to delete this event',
  LOGOUT: 'LOGOUT',
  CONFIRM_LOGOUT: 'Are you sure you want to logout?',
  CANCLE : 'cancel',
  DELETE_USER : 'Delete User',
  CONFIRM_DELETE_USER :'Are you sure you want to delete this user?',
  ADMIN_DELETE_USER :'Only admin can delete users',
  REGISTER_SUCCESS : 'You are registered successfully',
  SELECT_FORMAT_SLOT : 'Please select at least one format and slot',
  SOMETHING_WRONG : 'Something went wrong',
  SLOT_FULL_2V2 : 'Slot full, 2v2 slots are full',
  DEADLINE : 'Registration closed, Deadline has passed',
  EVENT_NOT_FOUND : 'Event not found',
  SLOT_FULL : 'Slot Full',
  EVENT_CREATION_ALLOWED : 'Only admin or organiser can create events',
  ALREADY_JOINED_EVENT : 'Already Joined Event',
  PARTICIPANTS_ALLOWED : 'Only participants are allowed'
};
